config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :accessories
  resources :mobiles
  root to: 'mobiles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  belongs_to :mobile
  has_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mobile.rb
class Mobile < ApplicationRecord
    has_many :orders
    has_many :accessories
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :accessories
  belongs_to :mobile
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_accessory, only: [:show, :edit, :update, :destroy]

  # GET /accessories
  # GET /accessories.json
  def index
    @accessories = Accessory.all
  end

  # GET /accessories/1
  # GET /accessories/1.json
  def show
  end

  # GET /accessories/new
  def new
    @accessory = Accessory.new
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories
  # POST /accessories.json
  def create
    @accessory = Accessory.new(accessory_params)

    respond_to do |format|
      if @accessory.save
        format.html { redirect_to @accessory, notice: 'Accessory was successfully created.' }
        format.json { render :show, status: :created, location: @accessory }
      else
        format.html { render :new }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories/1
  # PATCH/PUT /accessories/1.json
  def update
    respond_to do |format|
      if @accessory.update(accessory_params)
        format.html { redirect_to @accessory, notice: 'Accessory was successfully updated.' }
        format.json { render :show, status: :ok, location: @accessory }
      else
        format.html { render :edit }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories/1
  # DELETE /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to accessories_url, notice: 'Accessory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accessory_params
      params.require(:accessory).permit(:name, :price, :discription, :mobile_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mobile, only: [:show, :edit, :update, :destroy]

  # GET /mobiles
  # GET /mobiles.json
  def index
    @mobiles = Mobile.all
  end

  # GET /mobiles/1
  # GET /mobiles/1.json
  def show
  end

  # GET /mobiles/new
  def new
    @mobile = Mobile.new
  end

  # GET /mobiles/1/edit
  def edit
  end

  # POST /mobiles
  # POST /mobiles.json
  def create
    @mobile = Mobile.new(mobile_params)

    respond_to do |format|
      if @mobile.save
        format.html { redirect_to @mobile, notice: 'Mobile was successfully created.' }
        format.json { render :show, status: :created, location: @mobile }
      else
        format.html { render :new }
        format.json { render json: @mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mobiles/1
  # PATCH/PUT /mobiles/1.json
  def update
    respond_to do |format|
      if @mobile.update(mobile_params)
        format.html { redirect_to @mobile, notice: 'Mobile was successfully updated.' }
        format.json { render :show, status: :ok, location: @mobile }
      else
        format.html { render :edit }
        format.json { render json: @mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mobiles/1
  # DELETE /mobiles/1.json
  def destroy
    @mobile.destroy
    respond_to do |format|
      format.html { redirect_to mobiles_url, notice: 'Mobile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mobile
      @mobile = Mobile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mobile_params
      params.require(:mobile).permit(:title, :model, :color, :price, :discription)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :price, :amount_paid, :amount_balance, :discription, :accessories_id, :mobile_id)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/accessories/_form.html.erb
<%= form_for(accessory) do |f| %>
  <% if accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accessory.errors.count, "error") %> prohibited this accessory from being saved:</h2>

      <ul>
      <% accessory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :discription %>
    <%= f.text_field :discription %>
  </div>

  <div class="field">
    <%= f.label :mobile_id %>
    <%= f.text_field :mobile_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accessories/edit.html.erb
<h1>Editing Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Show', @accessory %> |
<%= link_to 'Back', accessories_path %>

app/views/accessories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accessories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Discription</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= accessory.name %></td>
        <td><%= accessory.price %></td>
        <td><%= accessory.discription %></td>
        <td><%= accessory.mobile %></td>
        <td><%= link_to 'Show', accessory %></td>
        <td><%= link_to 'Edit', edit_accessory_path(accessory) %></td>
        <td><%= link_to 'Destroy', accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory', new_accessory_path %>

app/views/accessories/new.html.erb
<h1>New Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Back', accessories_path %>

app/views/accessories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @accessory.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @accessory.price %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @accessory.discription %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @accessory.mobile %>
</p>

<%= link_to 'Edit', edit_accessory_path(@accessory) %> |
<%= link_to 'Back', accessories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobileadmin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/mobiles/_form.html.erb
<%= form_for(mobile) do |f| %>
  <% if mobile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mobile.errors.count, "error") %> prohibited this mobile from being saved:</h2>

      <ul>
      <% mobile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :discription %>
    <%= f.text_field :discription %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mobiles/edit.html.erb
<h1>Editing Mobile</h1>

<%= render 'form', mobile: @mobile %>

<%= link_to 'Show', @mobile %> |
<%= link_to 'Back', mobiles_path %>

app/views/mobiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mobiles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Model</th>
      <th>Color</th>
      <th>Price</th>
      <th>Discription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mobiles.each do |mobile| %>
      <tr>
        <td><%= mobile.title %></td>
        <td><%= mobile.model %></td>
        <td><%= mobile.color %></td>
        <td><%= mobile.price %></td>
        <td><%= mobile.discription %></td>
        <td><%= link_to 'Show', mobile %></td>
        <td><%= link_to 'Edit', edit_mobile_path(mobile) %></td>
        <td><%= link_to 'Destroy', mobile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mobile', new_mobile_path %>

app/views/mobiles/new.html.erb
<h1>New Mobile</h1>

<%= render 'form', mobile: @mobile %>

<%= link_to 'Back', mobiles_path %>

app/views/mobiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mobile.title %>
</p>

<p>
  <strong>Model:</strong>
  <%= @mobile.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @mobile.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @mobile.price %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @mobile.discription %>
</p>

<%= link_to 'Edit', edit_mobile_path(@mobile) %> |
<%= link_to 'Back', mobiles_path %>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :amount_paid %>
    <%= f.number_field :amount_paid %>
  </div>

  <div class="field">
    <%= f.label :amount_balance %>
    <%= f.text_field :amount_balance %>
  </div>

  <div class="field">
    <%= f.label :discription %>
    <%= f.text_field :discription %>
  </div>

  <div class="field">
    <%= f.label :accessories_id %>
    <%= f.text_field :accessories_id %>
  </div>

  <div class="field">
    <%= f.label :mobile_id %>
    <%= f.text_field :mobile_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Amount paid</th>
      <th>Amount balance</th>
      <th>Discription</th>
      <th>Accessories</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.price %></td>
        <td><%= order.amount_paid %></td>
        <td><%= order.amount_balance %></td>
        <td><%= order.discription %></td>
        <td><%= order.accessories %></td>
        <td><%= order.mobile %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Amount paid:</strong>
  <%= @order.amount_paid %>
</p>

<p>
  <strong>Amount balance:</strong>
  <%= @order.amount_balance %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @order.discription %>
</p>

<p>
  <strong>Accessories:</strong>
  <%= @order.accessories %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @order.mobile %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>